feat(home): add react bootstrap package and create home page
analuciabolico/sgtcc-front pull request #14
Opened 2021-06-14 01:37 UTC by anakettl

### Feat
Create home page and add react bootstrap.
Delete unnecessary files

The buttons and the routes will be styled in the next pr

![image](https://user-images.githubusercontent.com/47605984/121829011-bc86a200-cc97-11eb-8fb1-35f6aee4e6b1.png)

2021-06-14 01:56 UTC, analuciabolico commented on src/pages/Home/styles.module.scss
> +  color: var(--color-text-in-primary);
Pq está usando o --color ao invés de usar as variáveis que estamos?

2021-06-14 02:00 UTC, analuciabolico commented on package.json
> +    "bootstrap": "^4.6.0",
Não precisa desse, e somente o do react-bootstrap, na verdade faltou um import dos CSS para ele pegar os js/css

2021-06-14 02:01 UTC, analuciabolico requested changes
Tem que alterar essas coisas que eu falei, mas são Minors, eu posso fazer sipa amanhã daí eu te aviso. Pq eu faço nesse mesmo PR mesmo

2021-06-27 01:02 UTC, analuciabolico commented on src/pages/Home/styles.module.scss
> +  color: var(--color-text-in-primary);
ajustado

2021-06-27 01:02 UTC, analuciabolico commented on package.json
> +    "bootstrap": "^4.6.0",
ajustado

2021-06-27 01:05 UTC, analuciabolico approved these changes

2021-06-27 13:13 UTC, anakettl commented
Testado e funcionando!

2021-06-27 17:34 UTC, merged